const{chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
(async()=>{
 const folder=path.resolve(process.argv[2]),real=path.resolve(process.argv[3]),out=path.join(folder,'share-picker-validation');fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),context=await browser.newContext({acceptDownloads:true});await context.setOffline(true);const page=await context.newPage(),errors=[],requests=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 const open=async()=>{if(await page.locator('#bookShareMenu').isHidden())await page.locator('#bookShareTrigger').click();};
 const goto=async file=>{await page.goto(pathToFileURL(file).href);await page.evaluate(()=>document.fonts.ready);};const pass=n=>checks.push(n);
 await goto(real);const data=await page.locator('#reading-data').evaluate(n=>JSON.parse(n.textContent)),N=data.books.length;
 assert.equal(await page.locator('#sharePages [data-page]').count(),4);assert.equal(await page.locator('#sharePages [data-page]:checked').count(),4);assert.equal(await page.locator('#bookShareRows [data-page]').count(),N);assert.equal(await page.locator('[data-page]:checked').count(),N+4);assert((await page.locator('#selectedCount').textContent()).includes(`${N+4}／${N+4}`));pass('all loaded books and four overview pages default selected dynamically');
 const nonFeatured=data.books.find(b=>!b.selected)||data.books.at(-1);await open();await page.locator(`[data-preview="book-${nonFeatured.book_id}"]`).click();await page.waitForFunction(title=>document.querySelector('#previewTitle').textContent===title,nonFeatured.title);assert(!(await page.locator('#bookShareMenu').isHidden()));pass('non-featured books preview without closing multi-select');
 const target=page.locator(`[data-page="book-${nonFeatured.book_id}"]`);await target.uncheck();assert((await page.locator('#bookShareCount').textContent()).includes(`${N-1}／${N}`));assert(await page.locator('#bookShareTrigger').getAttribute('aria-expanded').then(s=>s==='true'));assert(await target.evaluate(n=>n===document.activeElement));pass('checkbox updates count and retains keyboard focus');
 await page.locator('#closeShareBooks').click();assert(await page.locator('#bookShareMenu').isHidden());await page.locator('#undoSelection').click();assert(await target.isChecked());pass('undo restores book selection');
 await open();await page.locator('#shareBookSearch').fill(nonFeatured.title);assert.equal(await page.locator('#bookShareRows .share-page:visible').count(),1);assert.equal(await page.locator('[data-page]:checked').count(),N+4);pass('search filters display without changing selected pages');
 await page.locator('#shareBookSearch').fill('不存在的书籍xyz');assert(await page.locator('#shareBookEmpty').isVisible());await page.locator('#shareBookSearch').fill('');await page.locator('#clearShareBooks').click();assert.equal(await page.locator('[data-page]:checked').count(),4);await page.locator('#selectAllShareBooks').click();assert.equal(await page.locator('[data-page]:checked').count(),N+4);pass('all/none acts on books independently of four overview pages');
 await page.keyboard.press('Escape');assert.equal(await page.locator('#bookShareTrigger').getAttribute('aria-expanded'),'false');assert(await page.locator('#bookShareTrigger').evaluate(n=>n===document.activeElement));pass('Escape restores trigger focus');
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:950});await page.locator('#bookShareTrigger').scrollIntoViewIfNeeded();await open();const rect=await page.locator('#bookShareMenu').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=width+1);assert(rect.y>=0&&rect.y+rect.height<=951);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)));await page.screenshot({path:path.join(out,`picker-${width}.png`)});await page.keyboard.press('Escape');pass(`multi-select stays in viewport ${width}`);}
 await page.setViewportSize({width:1440,height:950});await open();await page.locator('#clearShareBooks').click();await page.locator(`[data-page="book-${nonFeatured.book_id}"]`).check();await page.locator('#bookShareTrigger').click();
 const[download]=await Promise.all([page.waitForEvent('download'),page.locator('#exportGroup').click()]);await download.saveAs(path.join(out,'selected.zip'));const bytes=fs.readFileSync(path.join(out,'selected.zip'));assert.equal(bytes.readUInt16LE(bytes.length-22+10),5);assert(!(await page.locator('#bookShareTrigger').isDisabled()));pass('ZIP contains four overview pages plus the selected book and controls recover');
 await goto(path.join(folder,'empty.html'));assert.equal(await page.locator('[data-page]:checked').count(),4);assert(await page.locator('#bookShareTrigger').isDisabled());await page.locator('[data-preview="timeline"]').click();await page.waitForFunction(()=>document.querySelector('#previewTitle').textContent==='阅读时间线');
 const texts=await page.evaluate(async()=>{const log=[],old=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){log.push(String(text));return old.call(this,text,...args);};document.querySelector('[data-preview="timeline"]').click();await new Promise(r=>setTimeout(r,100));CanvasRenderingContext2D.prototype.fillText=old;return log;});assert(texts.some(t=>t.includes('暂无带日期')));pass('zero books retain four default overview pages and an honest timeline empty state');
 const[zero]=await Promise.all([page.waitForEvent('download'),page.locator('#exportGroup').click()]);await zero.saveAs(path.join(out,'zero.zip'));const z=fs.readFileSync(path.join(out,'zero.zip'));assert.equal(z.readUInt16LE(z.length-22+10),4);pass('zero-book year exports four actual pages');
 await goto(path.join(folder,'many.html'));const many=await page.locator('#reading-data').evaluate(n=>JSON.parse(n.textContent).books.length);assert.equal(await page.locator('[data-page]:checked').count(),many+4);await open();assert((await page.locator('#bookShareCount').textContent()).includes(`／${many}`));assert(await page.locator('#bookShareRows').evaluate(n=>n.scrollHeight>n.clientHeight));await page.locator('#shareBookSearch').fill('书名最后一本');assert.equal(await page.locator('#bookShareRows .share-page:visible').count(),1);pass('large varying book count scrolls and searches with no fixed-count assumptions');
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);pass('no network or runtime errors');await browser.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({status:'pass',checks},null,2));console.log(JSON.stringify({status:'pass',checks:checks.length,out}));
})().catch(e=>{console.error(e);process.exit(1)});
